include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
    - lib/generated/*
    - lib/**/*.g.dart
    - assets/**/*.gen.dart
    - packages/**/*.gen.dart
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
