include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    switch_on_type: ignore
    lines_longer_than_80_chars: ignore
    avoid_print: ignore
    inference_failure_on_instance_creation: ignore
    discarded_futures: ignore
    non_constant_identifier_names: ignore
linter:
  rules:
    public_member_api_docs: false
    prefer_constructors_over_static_methods: false
