include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    switch_on_type: ignore
linter:
  rules:
    public_member_api_docs: false
    prefer_constructors_over_static_methods: false
