#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run Flutter format
echo "Running dart format..."
dart format --set-exit-if-changed .

# Run Flutter analyze
echo "Running flutter analyze..."
flutter analyze

# Run Flutter tests
echo "Running flutter test..."
flutter test --coverage --test-randomize-ordering-seed random

# Check the exit status of the previous command (flutter analyze and test)
if [ $? -ne 0 ]; then
    echo "Flutter analyze or test failed. Please fix the issues and try again."
    exit 1
else
    echo "Flutter analyze and test passed."
    exit 0 # Allow the commit
fi
