#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run Flutter format
echo "Running dart format..."
dart format --set-exit-if-changed .

# Run Flutter analyze
echo "Running flutter analyze..."
flutter analyze

# Run Flutter tests across all packages
echo "Running flutter tests in all packages..."
./scripts/run_tests.sh

# Check the exit status
if [ $? -ne 0 ]; then
    echo "❌ Pre-commit checks failed. Please fix the issues and try again."
    exit 1
else
    echo "✅ All checks passed!"
    exit 0 # Allow the commit
fi
